import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import type { Certification } from "@shared/schema";

interface CertificateOptions {
  certification: Certification;
  subscriptionTier: string;
  companyName?: string;
  companyLogoUrl?: string;
}

export async function generateCertificatePDF(options: CertificateOptions): Promise<Buffer> {
  const { certification, subscriptionTier, companyName, companyLogoUrl } = options;
  
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Generate QR code for proof URL
      const proofUrl = `${process.env.REPL_HOME || 'https://proofmint.com'}/proof/${certification.id}`;
      const qrCodeDataUrl = await QRCode.toDataURL(proofUrl, { width: 150 });

      // Header - emerald green background
      doc.rect(0, 0, doc.page.width, 120).fill('#10b981');
      
      // Logo/Shield icon (white)
      doc.fillColor('#ffffff')
         .fontSize(36)
         .font('Helvetica-Bold')
         .text('⬢', 50, 40, { width: 50, align: 'center' });
      
      // Title
      doc.fillColor('#ffffff')
         .fontSize(28)
         .font('Helvetica-Bold')
         .text('ProofMint Certificate', 120, 45);
      
      doc.fillColor('#ffffff')
         .fontSize(12)
         .font('Helvetica')
         .text('Blockchain Proof of Ownership', 120, 80);

      // Reset to black for body content
      doc.fillColor('#000000');

      // Certificate body
      let yPosition = 160;

      // Certification statement
      doc.fontSize(14)
         .font('Helvetica')
         .text('This certifies that the following file has been recorded on the', 50, yPosition, { width: 500, align: 'center' });
      
      yPosition += 20;
      doc.text('MultiversX blockchain with an immutable timestamp.', 50, yPosition, { width: 500, align: 'center' });

      yPosition += 50;

      // File information box
      doc.rect(50, yPosition, 495, 180).stroke('#e5e7eb');
      yPosition += 20;

      // File name
      doc.fontSize(11)
         .font('Helvetica-Bold')
         .text('File Name:', 70, yPosition);
      doc.font('Helvetica')
         .text(certification.fileName, 70, yPosition + 18, { width: 455 });

      yPosition += 50;

      // SHA-256 Hash
      doc.font('Helvetica-Bold')
         .text('SHA-256 Hash:', 70, yPosition);
      doc.font('Courier')
         .fontSize(9)
         .text(certification.fileHash, 70, yPosition + 18, { width: 455 });

      yPosition += 50;

      // Certification date
      doc.fontSize(11)
         .font('Helvetica-Bold')
         .text('Certification Date:', 70, yPosition);
      doc.font('Helvetica')
         .text(new Date(certification.createdAt || new Date()).toLocaleString('en-US', { 
           dateStyle: 'long', 
           timeStyle: 'short' 
         }), 70, yPosition + 18);

      yPosition += 50;

      // Author information
      if (certification.authorName) {
        doc.font('Helvetica-Bold')
           .text('Certified By:', 70, yPosition);
        doc.font('Helvetica')
           .text(certification.authorName, 70, yPosition + 18);
        
        if (certification.authorSignature) {
          doc.fontSize(9)
             .fillColor('#6b7280')
             .text(certification.authorSignature, 70, yPosition + 36);
          doc.fillColor('#000000').fontSize(11);
        }
      }

      yPosition += 100;

      // Blockchain verification section
      doc.fontSize(12)
         .font('Helvetica-Bold')
         .text('Blockchain Verification', 50, yPosition);

      yPosition += 25;

      // Transaction hash
      if (certification.transactionHash) {
        doc.fontSize(10)
           .font('Helvetica-Bold')
           .text('Transaction Hash:', 50, yPosition);
        doc.font('Courier')
           .fontSize(9)
           .text(certification.transactionHash, 50, yPosition + 16, { width: 350 });
      }

      // QR Code
      const qrImage = Buffer.from(qrCodeDataUrl.split(',')[1], 'base64');
      doc.image(qrImage, 420, yPosition - 10, { width: 120, height: 120 });
      
      doc.fontSize(8)
         .font('Helvetica')
         .fillColor('#6b7280')
         .text('Scan to verify', 440, yPosition + 115, { width: 80, align: 'center' });

      yPosition += 140;

      // Watermark for free tier
      if (subscriptionTier === 'free') {
        doc.fontSize(10)
           .fillColor('#d1d5db')
           .font('Helvetica')
           .text('Generated by ProofMint.com', 50, yPosition, { align: 'center', width: 495 });
      }

      // Custom branding for Business tier
      if (subscriptionTier === 'business' && companyName) {
        yPosition += 20;
        doc.fontSize(10)
           .fillColor('#6b7280')
           .font('Helvetica')
           .text(`Certified by ${companyName}`, 50, yPosition, { align: 'center', width: 495 });
      }

      // Footer
      yPosition = doc.page.height - 80;
      doc.fontSize(8)
         .fillColor('#9ca3af')
         .font('Helvetica')
         .text('This certificate is cryptographically verifiable on the MultiversX blockchain.', 50, yPosition, { align: 'center', width: 495 });
      
      doc.text('Visit the proof URL or scan the QR code to verify authenticity.', 50, yPosition + 15, { align: 'center', width: 495 });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
